"use client";
import { useEffect, useState } from "react";
import { MessageCircle, Send, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Toaster } from "@/components/ui/sonner";
import type { AlbumEntry, PublicMessage } from "@/lib/data";

export function PublicInteractions({ slug, album, initialComments, initialGuestbook }: { slug: string; album: AlbumEntry[]; initialComments: PublicMessage[]; initialGuestbook: PublicMessage[] }) {
  const [comments] = useState(initialComments); const [guestbook] = useState(initialGuestbook); const [busy, setBusy] = useState(false);
  const [likes, setLikes] = useState<Record<string, { count: number; liked: boolean }>>(() => Object.fromEntries(album.map((entry) => [entry.id, { count: Number(entry.like_count ?? 0), liked: false }])));
  useEffect(() => { const visitorKey = localStorage.getItem("nyangtori-visitor-key") ?? crypto.randomUUID(); localStorage.setItem("nyangtori-visitor-key", visitorKey); const likedIds = new Set(JSON.parse(localStorage.getItem("nyangtori-liked-photos") ?? "[]") as string[]); setLikes((current) => Object.fromEntries(Object.entries(current).map(([id, value]) => [id, { ...value, liked: likedIds.has(id) }]))); }, []);
  async function submit(path: string, payload: Record<string, string>, form: HTMLFormElement) { setBusy(true); const response = await fetch(`/api/public/${slug}/${path}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); setBusy(false); if (!response.ok) return toast.error((await response.json()).error ?? "등록하지 못했어요."); form.reset(); toast.success("마음을 남겼어요."); window.location.reload(); }
  async function remove(kind: "comments" | "guestbook", id: string) { const password = window.prompt("작성할 때 입력한 삭제 비밀번호를 입력해주세요."); if (!password) return; const response = await fetch(`/api/public/${slug}/${kind}/${id}`, { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ password }) }); if (!response.ok) return toast.error((await response.json()).error ?? "삭제하지 못했어요."); toast.success("삭제했어요."); window.location.reload(); }
  async function toggleLike(entryId: string) { const previous = likes[entryId] ?? { count: 0, liked: false }; const liked = !previous.liked; setLikes((current) => ({ ...current, [entryId]: { liked, count: Math.max(0, previous.count + (liked ? 1 : -1)) } })); const visitorKey = localStorage.getItem("nyangtori-visitor-key") ?? crypto.randomUUID(); localStorage.setItem("nyangtori-visitor-key", visitorKey); const response = await fetch(`/api/public/${slug}/likes`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ entryId, visitorKey, liked }) }); if (!response.ok) { setLikes((current) => ({ ...current, [entryId]: previous })); return toast.error("하트를 저장하지 못했어요."); } const result = await response.json() as { count: number }; setLikes((current) => ({ ...current, [entryId]: { liked, count: result.count } })); const likedIds = new Set(JSON.parse(localStorage.getItem("nyangtori-liked-photos") ?? "[]") as string[]); liked ? likedIds.add(entryId) : likedIds.delete(entryId); localStorage.setItem("nyangtori-liked-photos", JSON.stringify([...likedIds])); }
  return <><Toaster position="top-center" richColors /><div className="public-grid diary-grid">{album.map((entry) => { const src = entry.image_key ? `/api/media/${encodeURIComponent(entry.image_key)}` : entry.fallback_url ?? "/tori.png"; const entryComments = comments.filter((item) => item.album_entry_id === entry.id); const like = likes[entry.id] ?? { count: Number(entry.like_count ?? 0), liked: false }; return <article className="diary-card public-diary-card" key={entry.id}><div className="diary-photo"><img src={src} alt={entry.caption} />{entry.milestone && <span>{entry.milestone}</span>}<button className={`photo-heart ${like.liked ? "liked" : ""}`} onClick={() => void toggleLike(entry.id)} aria-label={like.liked ? "하트 취소" : "하트 남기기"} aria-pressed={like.liked}><span>♥</span><b>{like.count}</b></button></div><div className="diary-page"><time>{entry.taken_at.replaceAll("-", ".")}의 그림일기</time><h3>{entry.caption}</h3><details className="comment-box"><summary><MessageCircle />댓글 {entryComments.length}개</summary><div className="comment-list">{entryComments.map((item) => <p key={item.id}><strong>{item.nickname}</strong><span>{item.content}</span><button onClick={() => remove("comments", item.id)} aria-label="내 댓글 삭제"><Trash2 /></button></p>)}</div><form onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const fd = new FormData(form); void submit("comments", { albumEntryId: entry.id, nickname: String(fd.get("nickname") ?? ""), content: String(fd.get("content") ?? ""), password: String(fd.get("password") ?? ""), website: String(fd.get("website") ?? "") }, form); }}><input name="nickname" maxLength={20} required placeholder="닉네임" aria-label="닉네임" /><input name="content" maxLength={300} required placeholder="토리에게 댓글 남기기" aria-label="댓글" /><input name="password" type="password" minLength={4} maxLength={20} required placeholder="삭제 비밀번호" aria-label="삭제 비밀번호" /><input className="honey" name="website" tabIndex={-1} autoComplete="off" /><button disabled={busy} aria-label="댓글 등록"><Send /></button></form></details></div></article>; })}</div>
  <section className="guestbook"><div className="guestbook-title"><img src="/icon-share.png" alt="" /><div><span className="eyebrow">GUESTBOOK</span><h2>토리에게 인사 남기기</h2></div></div><form className="guestbook-form" onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const fd = new FormData(form); void submit("guestbook", { nickname: String(fd.get("nickname") ?? ""), content: String(fd.get("content") ?? ""), password: String(fd.get("password") ?? ""), website: String(fd.get("website") ?? "") }, form); }}><input name="nickname" maxLength={20} required placeholder="닉네임" /><textarea name="content" maxLength={300} required placeholder="토리에게 따뜻한 인사를 남겨주세요." /><input name="password" type="password" minLength={4} maxLength={20} required placeholder="삭제 비밀번호(4자 이상)" /><input className="honey" name="website" tabIndex={-1} autoComplete="off" /><button disabled={busy}><Send />방명록 남기기</button></form><div className="guestbook-list">{guestbook.map((item) => <article key={item.id}><strong>{item.nickname}</strong><p>{item.content}</p><time>{new Date(item.created_at).toLocaleDateString("ko-KR")}</time><button onClick={() => remove("guestbook", item.id)} aria-label="내 방명록 삭제"><Trash2 />삭제</button></article>)}</div></section></>;
}
